<div align="center">
    <img src="./images/zb-logo.png" alt="제로베이스" width="100%">
    <br>
    <a href="https://zerobaseschool.notion.site/DS-EDA-Lv-Test-b7d5e895c7cd4dda813c8fe2f2c23f79"><img src="./images/openinnotion_logo.png" alt="EDA Lv Test Doc" width="12%"></a>

이 Jupyter Notebook 파일은 <a href="https://zero-base.co.kr/category_data_camp/school_DS">제로베이스</a>에서 제공하는 **EDA Level Test** 문제입니다.<br>
지금까지 공부하신 내용으로 데이터 분석에 대해 좀 더 연습할 수 있는 시간이 되셨으면 좋겠습니다.🙂<br>
**EDA Level Test**에 대한 안내 사항은 상단 **Open in ZeroBase Notion** 로고를 클릭하여 확인해주세요!<br>
반드시 시작 전에 내용을 숙지해주시기를 바랍니다!<br>
</div>

***

<h1 style="background-color:#9F81F7;color:#D8D8D8;font-weight:bold;display:inline-block;padding: 5px">EDA Level Test 05 ⭐️⭐️</h1>

| Week | Data Analysis | Difficulty | This Notebook |
|------|---------------|------------|-------|
| 1    | 서울시 인구 데이터 | ⭐️ ||
| 2    | 화장품 성분 데이터 | ⭐️⭐️⭐️ ||
| 3    | 올림픽 데이터 | ⭐️⭐️ ||
| 4    | 국가별 인터넷 사용률 데이터 |⭐️⭐️ ||
| 5    | 전국 박물관/미술관 정보 표준 데이터 | ⭐️⭐️⭐️ |👈|
| 6    | 서울시 흡연율 통계 데이터 | ⭐️⭐️ ||
| 7    | 웹크롤링 | ⭐️ ||
| 8    | 서울시 지하철 호선별 역별 유/무임 승하차 인원 정보 데이터 | ⭐️⭐️ ||
| 9    | 서울시 교통사고 현황 (사고유형별) 통계 데이터 | ⭐️⭐️ ||
| 10   | 서울시 교통사고 현황 (사고유형별) 통계 + 서울시 차량통행속도 (구별/월별) 통계 + 서울시 인구밀도 (구별) 통계 | ⭐️⭐️⭐️ ||

## 문제 소개 및 데이터 준비 단계

### Target Data(Json): 전국박물관미술관정보표준데이터
- Source: [공공데이터포털](https://www.data.go.kr/data/15017323/standard.do)
- DownLoad: [전국박물관미술관정보표준데이터.json](https://www.data.go.kr/download/15017323/standard.do?dataType=json)


### 참고사항
- 공공데이터포털에서 해당 데이터는 다양한 Format(xls, xml, json, rdf, csv)으로 제공합니다.
<br></br>
- 다양한 Data Format 사용을 하고자 해당 Test에서는 일부러 json format의 데이터를 사용할 예정입니다.
    - json 상세 설명: https://www.json.org/json-ko.html
<br></br>
- 문제에 hint가 있을 경우, 해당 hint를 이용하지 않으셔도 무방합니다.

In [2]:
import json
# 채점을 위한 코드입니다. 반드시 실행해주세요.
from grading import *

with open('./datas/전국박물관미술관정보표준데이터.json', 'r', encoding='utf-8') as f:
    json_data = json.load(f)

## 문제 시작! 🏃🏻

## 1단계: Json Data로 DataFrame으로 만들기
***

### 문제 1-1) Json Data로 Pandas DataFrame 만들기 (10점) 
- 위에서 읽은 json_data는 아래와 같이 구성되어있습니다. 이를 참고하여 pandas dataframe으로 불러오세요.
<br></br>
    - json_data
        - json_data['fields']: List. 각 variable은 하나의 Column(열)을 의미하며, {id: Column(열)명}의 형식으로 구성 되어있습니다.
        - json_data['records']: List. 각 variable은 하나의 Row(행)을 의미하며, {Column(열)명: data}의 형식으로 구성 되어있습니다.
<br></br>
        - 예시
<br></br>
        <img src="./images/05-1-1-001.png" style="margin:auto" width=800/> 
<br></br>
    - 조건1: 위의 내용을 참고하여 'json_data'를 이용하여 Pandas DataFrame을 만드세요
<br></br>
    - 조건2: json data의 Index와 Column(열)의 순서(order)는 변경하지 마세요.
        - 앞에서부터 순차적으로 차례로 읽어 그대로 DataFrame으로 만드세요.
<br></br>
    - 조건3: 'df_target' 변수에 결과 DataFrame을 할당하세요.
<br></br>
<br></br>
    - hint: pandas의 read_json method로는 읽어지지 않습니다.
        - 공공데이터포털에서 json data를 만드는 형식이 read_json과 matching되지 않아 Error가 발생합니다.
<br></br>
<br></br>
- 완료 후 결과 DataFrame 변수(df_target)를 check_01_01 함수에 입력하여 채점하세요.

In [3]:
# 1-1
import pandas as pd

columns = [col['id'] for col in json_data['fields']]
df_target = pd.DataFrame(json_data['records'], columns=columns)
check_01_01(df_target)

정답입니다! 10점 누적 되었습니다!
현재 누적 점수: 10 / 100

In [4]:
df_target.head(2)

,시설명,박물관미술관구분,소재지도로명주소,소재지지번주소,위도,경도,운영기관전화번호,운영기관명,운영홈페이지,편의시설정보,...,청소년관람료,어린이관람료,관람료기타정보,박물관미술관소개,교통안내정보,관리기관전화번호,관리기관명,데이터기준일자,제공기관코드,제공기관명
0,풀짚공예박물관,사립,경기도 광주시 오포읍 문형산길 76,,37.36419778,127.1651063,031-717-4538,풀짚공예박물관,,,...,1500,1500,특별전시입장료-일반(3000)+특별전시입장료-미취학(1500)+특별전시입장료-유치원...,,,031-717-4538,풀짚공예박물관,2022-06-16,1371000,문화체육관광부
1,프라움 악기박물관,사립,경기도 남양주시 와부읍 경강로 756,,37.56850845,127.2270492,031-521-6043,프라움악기박물관,,,...,4000,3000,,,,031-521-6043,프라움 악기박물관,2022-06-16,1371000,문화체육관광부

## 2단계: DataFrame 전처리 01 - 기초
***

### 문제 2-1) 기초 전처리 01 (5점) 
- 1단계의 DataFrame(df_target)을 아래의 조건에 맞게 변경하세요.
<br></br>
    - 해당 json_data의 null값은 ""로 구성되어 df_target.info() 또는 df_target.isna() 등을 이용하여 null값을 확인할 경우 null값이 없다고 나오게 됩니다. 이에 이 Data를 제대로 확인하기 위해서 "" 대신에 Null값을 넣으려 합니다.
<br></br>
<br></br>
    - 조건1: ""(또는 '')는 띄어쓰기 없이 쌍따옴표(혹은 따옴표)로만 구성됩니다.
<br></br>
    - 조건2: ""(또는 '')를 null값(None)으로 바꾸세요.
<br></br>
    - 조건3: Index 또는 순서(order)는 변경하지 마세요.
<br></br>
    - 조건4: 'df_target' 변수에 결과 DataFrame을 할당하세요.
<br></br>
<br></br>
- 완료 후 결과 dataframe 변수(df_target)를 check_02_01 함수에 입력하여 채점하세요.

In [5]:
# 2-1

def find_null(value):
    
    value = None if value == '' else value
    
    return value

df_target = df_target.apply(lambda row: row.apply(find_null))
check_02_01(df_target)

정답입니다! 5점 누적 되었습니다!
현재 누적 점수: 15 / 100

In [6]:
df_target.head(2)

,시설명,박물관미술관구분,소재지도로명주소,소재지지번주소,위도,경도,운영기관전화번호,운영기관명,운영홈페이지,편의시설정보,...,청소년관람료,어린이관람료,관람료기타정보,박물관미술관소개,교통안내정보,관리기관전화번호,관리기관명,데이터기준일자,제공기관코드,제공기관명
0,풀짚공예박물관,사립,경기도 광주시 오포읍 문형산길 76,None,37.36419778,127.1651063,031-717-4538,풀짚공예박물관,None,None,...,1500,1500,특별전시입장료-일반(3000)+특별전시입장료-미취학(1500)+특별전시입장료-유치원...,None,None,031-717-4538,풀짚공예박물관,2022-06-16,1371000,문화체육관광부
1,프라움 악기박물관,사립,경기도 남양주시 와부읍 경강로 756,None,37.56850845,127.2270492,031-521-6043,프라움악기박물관,None,None,...,4000,3000,None,None,None,031-521-6043,프라움 악기박물관,2022-06-16,1371000,문화체육관광부

### 문제 2-2) 기초 전처리 02 (5점) 
- 2-1의 DataFrame(df_target)을 아래의 조건에 맞게 변경하세요.
<br></br>
    - json Data를 Pandas DataFrame으로 만들면서 수치형 데이터들이 string으로 인식되었습니다. 이를 변경하려고 합니다.
<br></br>
<br></br>
    - 조건1: 아래 type_int_col의 Column(열) Data를 정수(int)형 Data로 변경하세요.
<br></br>
    - 조건2: 아래 type_float_col의 Column(열) Data를 실수(float)형 Data로 변경하세요.
<br></br>
    - 조건3: 변경할 Data에 Null값이 있다면, 0으로 채우세요.
<br></br>
    - 조건4: Index 또는 순서(order)는 변경하지 마세요.
<br></br>
    - 조건5: 'df_target' 변수에 결과 DataFrame을 할당하세요.
<br></br>
<br></br>
- 완료 후 결과 dataframe 변수(df_target)를 check_02_02 함수에 입력하여 채점하세요.

In [8]:
type_int_col = ['어른관람료', '청소년관람료', '어린이관람료']
type_float_col = ['위도', '경도']

In [9]:
# 2-2

df_target[type_int_col+type_float_col] = df_target[type_int_col+type_float_col].fillna(0)
df_target[type_int_col] = df_target[type_int_col].apply(lambda row: row.apply(int))
df_target[type_float_col] = df_target[type_float_col].apply(lambda row: row.apply(float))
check_02_02(df_target)

정답입니다! 5점 누적 되었습니다!
현재 누적 점수: 20 / 100

In [10]:
df_target.head(2)

,시설명,박물관미술관구분,소재지도로명주소,소재지지번주소,위도,경도,운영기관전화번호,운영기관명,운영홈페이지,편의시설정보,...,청소년관람료,어린이관람료,관람료기타정보,박물관미술관소개,교통안내정보,관리기관전화번호,관리기관명,데이터기준일자,제공기관코드,제공기관명
0,풀짚공예박물관,사립,경기도 광주시 오포읍 문형산길 76,None,37.364198,127.165106,031-717-4538,풀짚공예박물관,None,None,...,1500,1500,특별전시입장료-일반(3000)+특별전시입장료-미취학(1500)+특별전시입장료-유치원...,None,None,031-717-4538,풀짚공예박물관,2022-06-16,1371000,문화체육관광부
1,프라움 악기박물관,사립,경기도 남양주시 와부읍 경강로 756,None,37.568508,127.227049,031-521-6043,프라움악기박물관,None,None,...,4000,3000,None,None,None,031-521-6043,프라움 악기박물관,2022-06-16,1371000,문화체육관광부

### 문제 2-3) 기초 전처리 03 (5점) 
- 2-2의 DataFrame(df_target)을 아래의 조건에 맞게 변경하세요.
<br></br>
    - 분석과 상관 없는 Column(열)의 Data들을 삭제하여 Data의 가독성을 높이고자 합니다.
<br></br>
<br></br>
    - 조건1: 아래 drop_col의 Column(열) Data를 삭제하세요.
<br></br>
    - 조건2: Index 또는 순서(order)는 변경하지 마세요.
<br></br>
    - 조건3: 'df_target' 변수에 결과 DataFrame을 할당하세요.
<br></br>
<br></br>
- 완료 후 결과 dataframe 변수(df_target)를 check_02_03 함수에 입력하여 채점하세요.

In [11]:
drop_cols = ['소재지지번주소', '위도', '경도', '운영기관전화번호','운영기관명', '운영홈페이지', '편의시설정보', '휴관정보', 
            '관람료기타정보', '박물관미술관소개', '교통안내정보', '관리기관전화번호', '관리기관명', '제공기관코드', '제공기관명']

In [12]:
# 2-3

df_target.drop(drop_cols, axis=1, inplace=True)
check_02_03(df_target)

정답입니다! 5점 누적 되었습니다!
현재 누적 점수: 25 / 100

In [13]:
df_target.head(2)

,시설명,박물관미술관구분,소재지도로명주소,평일관람시작시각,평일관람종료시각,공휴일관람시작시각,공휴일관람종료시각,어른관람료,청소년관람료,어린이관람료,데이터기준일자
0,풀짚공예박물관,사립,경기도 광주시 오포읍 문형산길 76,09:30,18:00,10:00,18:00,3000,1500,1500,2022-06-16
1,프라움 악기박물관,사립,경기도 남양주시 와부읍 경강로 756,00:00,23:59,00:00,23:59,5000,4000,3000,2022-06-16

### 문제 2-4) 기초 전처리 04 (5점) 
- 2-3의 DataFrame(df_target)을 아래의 조건에 맞게 변경하세요.
<br></br>
    - 어른, 청소년, 어린이 관람료가 이상한 경우, 해당 row(행) data 자체가 이상하다고 판단하여 삭제하고자 합니다.
<br></br>
<br></br>
    - 조건1: 관람료와 관련된 Column(열)은 위에서 정의한 type_int_col 입니다.
<br></br>
    - 조건2: 관람료가 10원 단위로 나누어 떨어지지 않는 경우 이상치로 판단합니다. 해당 row(행)를 삭제하세요.
<br></br>
    - 조건3: 관람료가 100000원(십만원) 이상인 경우 이상치로 판단합니다. 해당 row(행)를 삭제하세요.
<br></br>
    - 조건4: Index 또는 순서(order)는 변경하지 마세요.
<br></br>
    - 조건5: 'df_target' 변수에 결과 DataFrame을 할당하세요.
<br></br>
<br></br>
- 완료 후 결과 dataframe 변수(df_target)를 check_02_04 함수에 입력하여 채점하세요.

In [14]:
# 2-4

type_int_col = ['어른관람료', '청소년관람료', '어린이관람료']
for col in type_int_col:
    df_target.drop(df_target[(df_target[col]%10 != 0) | (df_target[col] > 100000)].index, inplace=True, axis=0)
check_02_04(df_target)

정답입니다! 5점 누적 되었습니다!
현재 누적 점수: 30 / 100

In [15]:
df_target.head(2)

,시설명,박물관미술관구분,소재지도로명주소,평일관람시작시각,평일관람종료시각,공휴일관람시작시각,공휴일관람종료시각,어른관람료,청소년관람료,어린이관람료,데이터기준일자
0,풀짚공예박물관,사립,경기도 광주시 오포읍 문형산길 76,09:30,18:00,10:00,18:00,3000,1500,1500,2022-06-16
1,프라움 악기박물관,사립,경기도 남양주시 와부읍 경강로 756,00:00,23:59,00:00,23:59,5000,4000,3000,2022-06-16

## 3단계: DataFrame 전처리 02 - 심화
***

### 문제 3-1) 심화 전처리 01 (10점) 
- 2단계의 DataFrame(df_target)을 아래의 조건에 맞게 변경하세요.
<br></br>
    - 휴관중이거나 중복된 박물관/미술관의 data를 삭제하고자 합니다.
        - 아래의 조건 이외에도 중복되는 data들이 있으나, 해당 Test에서는 아래 조건에 따른 중복 data만 삭제하여 진행합니다.
<br></br>
<br></br>
    - 조건1: 시설명 Column(열) data에 '휴관'이라는 글자가 들어있으면 해당 row(행)은 삭제합니다.
<br></br>
    - 조건2: 시설명 Column(열) data가 중복되는 경우 해당 row(행)의 '데이터기준일자'가 최신인 data를 남기고 최신이 아닌 row(행)은 삭제합니다.
<br></br>
        - 만약, 시설명 Column(행)의 data가 중복되면서 가장 최신인 data가 두 개 이상인 경우, Index가 가장 낮은(예시: 495, 674 중 495) Index를 남기고, 높은 Index(예시: 495, 674 중 674)의 row(행) data를 삭제하세요.(낮은 인덱스가 더 최근 데이터라고 가정)
<br></br>
        - 예시: 아래 예시의 경우 데이터기준일자가 최신인 0번 index의 row(행)은 남기고 1338번 index의 row(행)은 삭제합니다.
<br></br>
        <img src="./images/05-3-1-001.png" style="margin:auto" width=800/>
<br></br>
    - 조건3: 시설명 Column(열) data의 중복 여부는 시설명 Column(열) data의 띄어쓰기를 삭제한 값이 일치할 경우 중복된 박물관/미술관으로 판단합니다.
<br></br>
        - 예시: 아래 예시의 경우 시설명 Column(열) data의 띄어쓰기를 삭제할 경우 시설명 Column(열) data가 동일합니다. 이에 데이터기준일자가 최신인 6번 index의 row(행)은 남기고 1909번 index의 row(행)은 삭제합니다.
<br></br>
        <img src="./images/05-3-1-002.png" style="margin:auto" width=800/> 
<br></br>
    - 조건4: Index 또는 순서(order)는 변경하지 마세요.
        - 문제를 풀기위해 순서를 변경하였다면, 다시 Index 순서로 정렬하세요
<br></br>
    - 조건5: 'df_target' 변수에 결과 DataFrame을 할당하세요.
<br></br>
<br></br>
    - hint1: '데이터기준일자' Column(열)의 Data는 현재 string입니다. 대소비교가 가능한지 확인해보세요.
<br></br>
    - hint2: 조건2 관련하여, '시설명'과 '데이터기준일자'가 같은 data들이 존재합니다. Index를 확인하세요.
        - '데이터기준일자' 기준으로 정렬시 주의하세요.
<br></br>
<br></br>
- 완료 후 결과 dataframe 변수(df_target)를 check_03_01 함수에 입력하여 채점하세요.

In [16]:
# 3-1

# 해당 문제에서는 데이터기준일자의 형식(년-월-일) 특성상 타입을 변경하지 않아도 정상적으로 대소비교 가능합니다..
# 따라서 아래 주석과 같이 format을 변경할 필요 없습니다.
# from datetime import date
# df_target.데이터기준일자 = df_target.데이터기준일자.apply(date.fromisoformat)

# 방법1
# 결과 dataframe에 index name이 지정되어있으나 방법2와 동일한 dataframe입니다.
df_target_temp = df_target.copy()

def replace_space(name):
    while ' ' in name:
        name = name.replace(' ', '')
    return name.strip()

df_target_temp['name_del_space'] = df_target_temp.시설명.apply(replace_space)

df_target_temp.drop(df_target_temp[df_target_temp.시설명.str.contains('휴관')].index, inplace=True)

not_unique_names = [name for name in df_target_temp.name_del_space.unique() if (df_target_temp.name_del_space == name).count() != 1]

df_target_temp.index.name = 'index'
df_target_temp.sort_values(by=['데이터기준일자', 'index'], ascending=[False, True], inplace=True)
df_target_temp = df_target_temp.loc[df_target_temp.name_del_space.drop_duplicates(keep='first').index]

df_target_temp.drop('name_del_space', axis=1, inplace=True)
df_target_temp.sort_index(inplace=True)
print('방법1')
check_03_01(df_target_temp)
display(df_target_temp.head())

# 방법2
df_target_temp = df_target.copy()

def replace_space(name):
    while ' ' in name:
        name = name.replace(' ', '')
    return name.strip()

df_target_temp['name_del_space'] = df_target_temp.시설명.apply(replace_space)

df_target_temp.drop(df_target_temp[df_target_temp.시설명.str.contains('휴관')].index, inplace=True)

not_unique_names = [name for name in df_target_temp.name_del_space.unique() if (df_target_temp.name_del_space == name).count() != 1]
for name in not_unique_names:
    temp_df = df_target_temp[(df_target_temp.name_del_space == name)]
    
    keep_idx = sorted(temp_df[(temp_df.데이터기준일자 == temp_df.데이터기준일자.max())].index)[0]
    del_idx = temp_df.index.drop(keep_idx)
    
    df_target_temp.drop(del_idx, inplace=True)
    
df_target_temp.drop('name_del_space', axis=1, inplace=True)
print('방법2')
check_03_01(df_target_temp)
display(df_target_temp.head())

df_target = df_target_temp.copy()

방법1
정답입니다! 10점 누적 되었습니다!
현재 누적 점수: 40 / 100

,시설명,박물관미술관구분,소재지도로명주소,평일관람시작시각,평일관람종료시각,공휴일관람시작시각,공휴일관람종료시각,어른관람료,청소년관람료,어린이관람료,데이터기준일자
index,,,,,,,,,,,
0,풀짚공예박물관,사립,경기도 광주시 오포읍 문형산길 76,09:30,18:00,10:00,18:00,3000,1500,1500,2022-06-16
1,프라움 악기박물관,사립,경기도 남양주시 와부읍 경강로 756,00:00,23:59,00:00,23:59,5000,4000,3000,2022-06-16
2,피노키오뮤지엄,사립,경기도 파주시 회동길 152(문발동),10:30,18:30,10:30,18:30,8000,8000,8000,2022-06-16
3,한과문화박물관한가원,사립,경기도 포천시 영북면 산정호수로 322번길 26-9,10:00,18:00,10:00,18:00,3000,1500,1500,2022-06-16
4,한국근현대사박물관,사립,경기도 파주시 탄현면 헤이리마을길 59-85,09:30,18:00,09:30,19:00,7000,5000,5000,2022-06-16

방법2
정답입니다! 10점 누적 되었습니다!
현재 누적 점수: 40 / 100

,시설명,박물관미술관구분,소재지도로명주소,평일관람시작시각,평일관람종료시각,공휴일관람시작시각,공휴일관람종료시각,어른관람료,청소년관람료,어린이관람료,데이터기준일자
0,풀짚공예박물관,사립,경기도 광주시 오포읍 문형산길 76,09:30,18:00,10:00,18:00,3000,1500,1500,2022-06-16
1,프라움 악기박물관,사립,경기도 남양주시 와부읍 경강로 756,00:00,23:59,00:00,23:59,5000,4000,3000,2022-06-16
2,피노키오뮤지엄,사립,경기도 파주시 회동길 152(문발동),10:30,18:30,10:30,18:30,8000,8000,8000,2022-06-16
3,한과문화박물관한가원,사립,경기도 포천시 영북면 산정호수로 322번길 26-9,10:00,18:00,10:00,18:00,3000,1500,1500,2022-06-16
4,한국근현대사박물관,사립,경기도 파주시 탄현면 헤이리마을길 59-85,09:30,18:00,09:30,19:00,7000,5000,5000,2022-06-16

### 문제 3-2) 심화 전처리 02 (10점) 
- 3-1의 DataFrame(df_target)을 아래의 조건에 맞게 변경하세요.
<br></br>
    - 평일과 공휴일에 박물관/미술관이 하루 중 몇시간이나 열려있는지를 알려주는 '관람가능시간'을 구하려고 합니다.
<br></br>
<br></br>
    - 조건1: 평일의 관람가능시간은 '평일관람시작시각'부터 '평일관람종료시각'까지 입니다. '평일관람가능시간' Column(열)을 만들어 평일의 관람가능시간을 입력하세요.
<br></br>
    - 조건2: 공휴일의 관람가능시간은 '공휴일관람시작시각'부터 '공휴일관람종료시각'까지 입니다. '공휴일관람가능시간' Column(열)을 만들어 공휴일의 관람가능시간을 입력하세요.
<br></br>
    - 조건3: '평일관람가능시간'과 '공휴일관람가능시간'은 시간(hour) 단위 실수(float)로 표기합니다.
<br></br>
        - 관람가능시간이 8시간 30분인경우 8.5로 표기합니다.
        - 관람가능시간이 23시간을 초과하는 경우 24시간으로 표기합니다.
        - 평일 또는 공휴일의 관람시작시각과 관람종료시각이 모두 00:00(또는 0:00)인 경우 휴일로 판단하며, 관람가능시간은 0으로 입력합니다.
        - 관람가능시간이 6시간 40분과 같이 무환소수(6.6666666666666......6666666667)로 표기될 경우 소숫점 셋째 자리에서 반올림하여 소숫점 둘째 자리까지 표기합니다.
<br></br>
        - 예시
<br></br>
        <img src="./images/05-3-2-001.png" style="margin:auto" width=800/> 
<br></br>
    - 조건4: Index 또는 순서(order)는 변경하지 마세요.
<br></br>
    - 조건5: 'df_target' 변수에 결과 DataFrame을 할당하세요.
<br></br>
<br></br>
    - hint: 각 관람시작시각/관람종료시각의 Data Type은 string 입니다.
<br></br>
<br></br>
- 완료 후 결과 dataframe 변수(df_target)를 check_03_02 함수에 입력하여 채점하세요.

In [17]:
# 3-2

# 아래 방법들은 새벽에 관람을 종료하는 박물관/미술관이 없음을 확인했기 때문에 가능한 코드입니다. 
# 만약 10:00(관람시작시각) ~ 02:00(관람종료시각)이라면, 하기 코드로는 음수(-8)가 나오기때문에 24를 더한 16시간이라고 표기되어야 합니다.

# 방법1
df_target_temp = df_target.copy()
def get_open_hour(row):
    from datetime import datetime
    
    now = datetime.now()

    open_str = row[row.index.str.contains('시작시각')][0]
    hour, minute = map(int, open_str.split(':'))
    open_datetime = now.replace(hour=hour, minute=minute, second=0, microsecond=0)

    close_str = row[row.index.str.contains('종료시각')][0]
    hour, minute = map(int, close_str.split(':'))
    close_datetime = now.replace(hour=hour, minute=minute, second=0, microsecond=0)

    open_time = round((close_datetime - open_datetime).seconds / 3600, 2)
    open_time = 24 if open_time > 23 else open_time
        
    return open_time

days_list = ['평일', '공휴일']
for day_str in days_list:
    target_cols = [f'{day_str}관람시작시각', f'{day_str}관람종료시각']
    df_target_temp[f'{day_str}관람가능시간'] = df_target_temp[target_cols].apply(get_open_hour, axis=1)
print('방법1')
check_03_02(df_target_temp)
display(df_target_temp.head())

# 방법2
df_target_temp = df_target.copy()
def get_open_hour(row):

    open_str = row[row.index.str.contains('시작시각')][0]
    hour, minute = map(int, open_str.split(':'))
    open_float = sum([hour, minute/60])

    close_str = row[row.index.str.contains('종료시각')][0]
    hour, minute = map(int, close_str.split(':'))
    close_float = sum([hour, minute/60])

    open_time = round(close_float - open_float, 2)
    open_time = 24 if open_time > 23 else open_time
        
    return open_time

days_list = ['평일', '공휴일']
for day_str in days_list:
    target_cols = [f'{day_str}관람시작시각', f'{day_str}관람종료시각']
    df_target_temp[f'{day_str}관람가능시간'] = df_target_temp[target_cols].apply(get_open_hour, axis=1)
print('방법2')
check_03_02(df_target_temp)
display(df_target_temp.head())

df_target = df_target_temp.copy()

방법1
정답입니다! 10점 누적 되었습니다!
현재 누적 점수: 50 / 100

,시설명,박물관미술관구분,소재지도로명주소,평일관람시작시각,평일관람종료시각,공휴일관람시작시각,공휴일관람종료시각,어른관람료,청소년관람료,어린이관람료,데이터기준일자,평일관람가능시간,공휴일관람가능시간
0,풀짚공예박물관,사립,경기도 광주시 오포읍 문형산길 76,09:30,18:00,10:00,18:00,3000,1500,1500,2022-06-16,8.5,8.0
1,프라움 악기박물관,사립,경기도 남양주시 와부읍 경강로 756,00:00,23:59,00:00,23:59,5000,4000,3000,2022-06-16,24.0,24.0
2,피노키오뮤지엄,사립,경기도 파주시 회동길 152(문발동),10:30,18:30,10:30,18:30,8000,8000,8000,2022-06-16,8.0,8.0
3,한과문화박물관한가원,사립,경기도 포천시 영북면 산정호수로 322번길 26-9,10:00,18:00,10:00,18:00,3000,1500,1500,2022-06-16,8.0,8.0
4,한국근현대사박물관,사립,경기도 파주시 탄현면 헤이리마을길 59-85,09:30,18:00,09:30,19:00,7000,5000,5000,2022-06-16,8.5,9.5

방법2
정답입니다! 10점 누적 되었습니다!
현재 누적 점수: 50 / 100

,시설명,박물관미술관구분,소재지도로명주소,평일관람시작시각,평일관람종료시각,공휴일관람시작시각,공휴일관람종료시각,어른관람료,청소년관람료,어린이관람료,데이터기준일자,평일관람가능시간,공휴일관람가능시간
0,풀짚공예박물관,사립,경기도 광주시 오포읍 문형산길 76,09:30,18:00,10:00,18:00,3000,1500,1500,2022-06-16,8.5,8.0
1,프라움 악기박물관,사립,경기도 남양주시 와부읍 경강로 756,00:00,23:59,00:00,23:59,5000,4000,3000,2022-06-16,24.0,24.0
2,피노키오뮤지엄,사립,경기도 파주시 회동길 152(문발동),10:30,18:30,10:30,18:30,8000,8000,8000,2022-06-16,8.0,8.0
3,한과문화박물관한가원,사립,경기도 포천시 영북면 산정호수로 322번길 26-9,10:00,18:00,10:00,18:00,3000,1500,1500,2022-06-16,8.0,8.0
4,한국근현대사박물관,사립,경기도 파주시 탄현면 헤이리마을길 59-85,09:30,18:00,09:30,19:00,7000,5000,5000,2022-06-16,8.5,9.5

### 문제 3-3) 심화 전처리 03 (10점) 
- 3-2의 DataFrame(df_target)을 아래의 조건에 맞게 변경하세요.
<br></br>
    - '소재지도로명주소' Column(열)의 Data를 가공하여 광역자치단체-기초자치단체(행정시)-상세 주소로 구분하려고 합니다.
<br></br>
<br></br>
    - 조건1: '소재재도로명주소' Column(열) data의 첫번째 단어는 언제나 광역자치단체명을 의미합니다. '광역' Column(열)을 만들어 해당 row(행) data의 광역자치단체명을 입력하세요.
        - '세종특별시'는 현재 '세종특별자차시'로 명칭이 변경되었습니다. 이를 반영해주세요.
<br></br>
    - 조건2: '소재재도로명주소' Column(열) data의 두번째 단어는 대부분 기초자치단체명을 의미합니다. '기초' Column(열)을 만들어 해당 row(행) data의 기초자치단체명을 입력하세요.
        - '제주특별자치도'의 경우 기초자치단체가 없으나, 행정시('제주시', '서귀포시')가 '소재재도로명주소' Column(열) data의 두번째 단어에 위치합니다. 행정시를 '기초' Column(열)에 입력하세요.
        - '세종특별자치시'의 경우 기초자치단체가 없습니다. '세종특별자치시'의 경우 '기초' Column(열)에는 Null값(None)을 입력해주세요.
<br></br>
    - 조건3: '소재재도로명주소' Column(열) data에서 광역/기초자치단체(행정시포함)에 포함되지 않은 데이터는 '상세' Column(열)을 만들어 입력하세요.
<br></br>
        - 예시
<br></br>
        <img src="./images/05-3-3-001.png" style="margin:auto" width=800/> 
<br></br>
    - 조건4: '소재지도로명주소', '광역', '기초', '상세 Column(행)의 data는 해당 data의 앞-뒤로 띄어쓰기 등 공백이 없어야 합니다.
<br></br>
    - 조건5: Index 또는 순서(order)는 변경하지 마세요.
<br></br>
    - 조건6: 'df_target' 변수에 결과 DataFrame을 할당하세요.
<br></br>
<br></br>
- 완료 후 결과 dataframe 변수(df_target)를 check_03_03 함수에 입력하여 채점하세요.

In [18]:
# 3-3

# 방법1
df_target_temp = df_target.copy()
def split_address(address):
    from collections import deque

    address_split = deque(address.split(' '))

    province = address_split.popleft()
    province = '세종특별자치시' if province == '세종특별시' else province

    city = address_split.popleft().strip() if province != '세종특별자치시' else None
    
    detail = ' '.join(address_split)

    return pd.Series([address.strip(), province.strip(), city, detail.strip()])

df_target_temp[['소재지도로명주소', '광역', '기초', '상세']] = df_target_temp.소재지도로명주소.apply(split_address)
print('방법1')
check_03_03(df_target_temp)
display(df_target_temp.head())

# 방법2
df_target_temp = df_target.copy()
def split_address(address):
    
    address_split = address.split(' ')

    province = address_split[0]
    province = '세종특별자치시' if province == '세종특별시' else province

    if province == '세종특별자치시':
        city = None
        detail = ' '.join(address_split[1:])
    else:
        city = address_split[1].strip()
        detail = ' '.join(address_split[2:])

    return pd.Series([address.strip(), province.strip(), city, detail.strip()])

df_target_temp[['소재지도로명주소', '광역', '기초', '상세']] = df_target_temp.소재지도로명주소.apply(split_address)
print('방법2')
check_03_03(df_target_temp)
display(df_target_temp.head())

df_target = df_target_temp.copy()

방법1
정답입니다! 10점 누적 되었습니다!
현재 누적 점수: 60 / 100

,시설명,박물관미술관구분,소재지도로명주소,평일관람시작시각,평일관람종료시각,공휴일관람시작시각,공휴일관람종료시각,어른관람료,청소년관람료,어린이관람료,데이터기준일자,평일관람가능시간,공휴일관람가능시간,광역,기초,상세
0,풀짚공예박물관,사립,경기도 광주시 오포읍 문형산길 76,09:30,18:00,10:00,18:00,3000,1500,1500,2022-06-16,8.5,8.0,경기도,광주시,오포읍 문형산길 76
1,프라움 악기박물관,사립,경기도 남양주시 와부읍 경강로 756,00:00,23:59,00:00,23:59,5000,4000,3000,2022-06-16,24.0,24.0,경기도,남양주시,와부읍 경강로 756
2,피노키오뮤지엄,사립,경기도 파주시 회동길 152(문발동),10:30,18:30,10:30,18:30,8000,8000,8000,2022-06-16,8.0,8.0,경기도,파주시,회동길 152(문발동)
3,한과문화박물관한가원,사립,경기도 포천시 영북면 산정호수로 322번길 26-9,10:00,18:00,10:00,18:00,3000,1500,1500,2022-06-16,8.0,8.0,경기도,포천시,영북면 산정호수로 322번길 26-9
4,한국근현대사박물관,사립,경기도 파주시 탄현면 헤이리마을길 59-85,09:30,18:00,09:30,19:00,7000,5000,5000,2022-06-16,8.5,9.5,경기도,파주시,탄현면 헤이리마을길 59-85

방법2
정답입니다! 10점 누적 되었습니다!
현재 누적 점수: 60 / 100

,시설명,박물관미술관구분,소재지도로명주소,평일관람시작시각,평일관람종료시각,공휴일관람시작시각,공휴일관람종료시각,어른관람료,청소년관람료,어린이관람료,데이터기준일자,평일관람가능시간,공휴일관람가능시간,광역,기초,상세
0,풀짚공예박물관,사립,경기도 광주시 오포읍 문형산길 76,09:30,18:00,10:00,18:00,3000,1500,1500,2022-06-16,8.5,8.0,경기도,광주시,오포읍 문형산길 76
1,프라움 악기박물관,사립,경기도 남양주시 와부읍 경강로 756,00:00,23:59,00:00,23:59,5000,4000,3000,2022-06-16,24.0,24.0,경기도,남양주시,와부읍 경강로 756
2,피노키오뮤지엄,사립,경기도 파주시 회동길 152(문발동),10:30,18:30,10:30,18:30,8000,8000,8000,2022-06-16,8.0,8.0,경기도,파주시,회동길 152(문발동)
3,한과문화박물관한가원,사립,경기도 포천시 영북면 산정호수로 322번길 26-9,10:00,18:00,10:00,18:00,3000,1500,1500,2022-06-16,8.0,8.0,경기도,포천시,영북면 산정호수로 322번길 26-9
4,한국근현대사박물관,사립,경기도 파주시 탄현면 헤이리마을길 59-85,09:30,18:00,09:30,19:00,7000,5000,5000,2022-06-16,8.5,9.5,경기도,파주시,탄현면 헤이리마을길 59-85

## 4단계: 원하는 정보 얻기
***

### 문제 4-1) 원하는 정보 얻기 01 (10점)
- 3단계의 DataFrame(df_target)을 이용하여 아래의 조건에 맞는 정보를 구하세요.
<br></br>
    - 광역자치단체별 박물관/미술관의 총 수를 확인하고자 합니다.
<br></br>
<br></br>
    - 조건1: df_target의 '광역' Column(열)에 있는 광역자치단체 data를 이용하여 광역자치단체별 박물관/미술관의 총 수를 나타내주세요.
<br></br>
    - 조건2: 결과 DataFrame의 Index는 광역자치단체입니다. 광역자치단체의 우선순위는 아래 province_dict의 value(값)으로 제공합니다. Index의 순서를 광역자치단체의 우선순위에 따라 나열해주세요.
        - 출처: [행정안전부](https://www.mois.go.kr/frt/sub/a04/localGovernment/screen.do)
<br></br>
    - 조건3: 결과 DataFrame의 박물관/미술관의 총 수를 나타내는 Column(열)의 이름은 '박물관미술관수' 입니다.
<br></br>
        - 예시: Index/Column
<br></br>
        <img src="./images/05-4-1-001.png" style="margin:auto" width=200/> 
<br></br>
    - 조건4: 'df_result' 변수에 결과 DataFrame을 할당하세요.
<br></br>
<br></br>
- 완료 후 결과 dataframe 변수(df_result)를 check_04_01 함수에 입력하여 채점하세요.

In [19]:
province_dict = {
    '서울특별시': 0,
    '부산광역시': 1,
    '대구광역시': 2,
    '인천광역시': 3,
    '광주광역시': 4,
    '대전광역시': 5,
    '울산광역시': 6,
    '세종특별자치시': 7,
    '경기도': 8,
    '강원도': 9,
    '충청북도': 10,
    '충청남도': 11,
    '전라북도': 12,
    '전라남도': 13,
    '경상북도': 14,
    '경상남도': 15,
    '제주특별자치도': 16
}

In [20]:
# 4-1

# 방법1
df_result = pd.DataFrame(df_target.groupby(['광역']).count().iloc[:,0]).rename({'시설명':'박물관미술관수'}, axis=1)
df_result = df_result.iloc[df_result.index.map(province_dict).argsort()]
print('방법1')
check_04_01(df_result)
display(df_result)

# 방법2
df_result = pd.DataFrame(df_target.groupby(['광역']).count().iloc[:,0]).rename({'시설명':'박물관미술관수'}, axis=1)
df_result.sort_index(key=lambda x: x.map(province_dict), inplace=True)
print('방법2')
check_04_01(df_result)
display(df_result)

방법1
정답입니다! 10점 누적 되었습니다!
현재 누적 점수: 70 / 100

         박물관미술관수
광역
서울특별시        198
부산광역시         48
대구광역시         23
인천광역시         42
광주광역시         49
대전광역시         23
울산광역시         11
세종특별자치시        8
경기도          219
강원도          133
충청북도          62
충청남도          76
전라북도          81
전라남도         107
경상북도          89
경상남도          97
제주특별자치도       95

방법2
정답입니다! 10점 누적 되었습니다!
현재 누적 점수: 70 / 100

         박물관미술관수
광역
서울특별시        198
부산광역시         48
대구광역시         23
인천광역시         42
광주광역시         49
대전광역시         23
울산광역시         11
세종특별자치시        8
경기도          219
강원도          133
충청북도          62
충청남도          76
전라북도          81
전라남도         107
경상북도          89
경상남도          97
제주특별자치도       95

### 문제 4-2) 원하는 정보 얻기 02 (10점)
- 3단계의 DataFrame(df_target)을 이용하여 아래의 조건에 맞는 정보를 구하세요.
<br></br>
    - 광역자치단체-기초자치단체(행정시)의 박물관/미술관의 총 수가 8개인 광역-기초자치단체(행정시)를 확인하고자 합니다.
<br></br>
<br></br>
    - 조건1: df_target의 '광역'과 '기초' Column(열)에 있는 광역자치단체/기초자치단체(행정시) data를 이용하여 광역자치단체-기초자치단체(행정시)별 박물관/미술관의 총 수가 8개인 곳을 찾아주세요.
<br></br>
    - 조건2: 결과 DataFrame의 '광역' Column(열)에 광역자치단체를, '기초' Column(열)에 기초자치단체(행정시)를 입력해주세요.
<br></br>
    - 조건3: '광역' Column(열)은 4-1문제와 같이 광역자치단체의 우선순위에 따라 나열해주세요.
        - 4-1의 province_dict 참고
<br></br>
    - 조건4: 같은 광역자치단체가 있다면, '기초' Column(열)의 data는 가나다 순의 역순으로 나열해주세요.
<br></br>
    - 조건5: 결과 DataFrame의 박물관/미술관의 총 수를 나타내는 Column(열)의 이름은 '박물관미술관수' 입니다.
<br></br>
        - 예시: 박물관미술관수가 9개인 광역-기초자치단체(행정시)
<br></br>
        <img src="./images/05-4-2-001.png" style="margin:auto" width=200/> 
<br></br>
    - 조건6: Index는 숫자(정수) 오름차순으로 설정해주세요.
<br></br>
    - 조건7: 'df_result' 변수에 결과 DataFrame을 할당하세요.
<br></br>
<br></br>
- 완료 후 결과 dataframe 변수(df_result)를 check_04_02 함수에 입력하여 채점하세요.

In [22]:
# 4-2
df_result = pd.DataFrame(df_target.groupby(['광역', '기초'], as_index=False, dropna=False).count().iloc[:,:3]).rename({'시설명':'박물관미술관수'}, axis=1)
df_result = df_result[df_result.박물관미술관수 == 8].sort_values(by='기초', ascending=False).sort_values(by='광역', key=lambda x: x.map(province_dict))
df_result.reset_index(drop=True, inplace=True)
check_04_02(df_result)

정답입니다! 10점 누적 되었습니다!
현재 누적 점수: 80 / 100

In [23]:
df_result.head(2)

      광역    기초  박물관미술관수
0  부산광역시  해운대구        8
1  인천광역시  미추홀구        8

### 문제 4-3) 원하는 정보 얻기 03 (10점)
- 3단계의 DataFrame(df_target)을 이용하여 아래의 조건에 맞는 정보를 구하세요.
<br></br>
    - 광역자치단체-박물관미술관구분(사립, 국립, 공립, 대학)의 평균 관람료 차이를 알아보고자 합니다.
<br></br>
<br></br>
    - 조건1: df_target의 '광역'과 '박물관미술관구분' Column(열)에 있는 광역자치단체/박물관미술관구분 data를 이용하여 광역자치단체-박물관미술관구분별 평균 어른관람료-평균 어린이관람료 간 차이가 가장 크고 작은 곳을 찾아주세요.
        - 단, 어른관람료 또는 어린이관람료가 둘 중 하나라도 0원(무료)인 박물관/미술관의 경우 평균 계산에서 제외해주세요.
<br></br>
    - 조건3: 결과 DataFrame의 '광역' Index에 광역자치단체를, '박물관미술관구분' Index에 박물관미술관구분를 입력해주세요.
<br></br>
    - 조건4: '광역' Index은 4-1문제와 같이 광역자치단체의 우선순위에 따라 나열해주세요.
        - 4-1의 province_dict 참고
<br></br>
    - 조건5: 결과 DataFrame의 '어른관람료' Column(열)은 광역자치단체-박물관미술관구분별 평균 어른 관람료를, '어린이관람료' Column(열)은 광역자치단체-박물관미술관구분별 평균 어린이 관람료를,  '관람료차이' Column(열)은 광역자치단체-박물관미술관구분별 평균 어른 관람료 - 평균 어린이 관람료(차액)을 입력해주세요.
        - 어른/어린이 관람료 및 관람료차이는 평균값에서 소숫점 첫째 자리에서 반올림한 정수 값을 입력해주세요.
            - 예시: 2978.5원 -> 2980.0원(소숫점 첫째 자리에서 반올림) -> 2980원(정수 값)
<br></br>
        - 예시: 청소년관람료-어린이관람료 차이가 가장 크고 작은 광역자치단체-박물관미술관구분
<br></br>
        <img src="./images/05-4-3-001.png" style="margin:auto" width=400/> 
<br></br>
    - 조건6: 'df_result' 변수에 결과 DataFrame을 할당하세요.
<br></br>
<br></br>
- 완료 후 결과 dataframe 변수(df_result)를 check_04_03 함수에 입력하여 채점하세요.

In [24]:
# 4-3
import numpy as np

df_result = df_target[(df_target.어른관람료 != 0)&(df_target.어린이관람료 != 0)][['광역', '박물관미술관구분', '어른관람료', '어린이관람료']].groupby(['광역', '박물관미술관구분']).agg(lambda x: int(round(np.average(x), -1)))
df_result.sort_index(level=0, key=lambda x: x.map(province_dict), inplace=True)
df_result['관람료차이'] = df_result.어른관람료 - df_result.어린이관람료

df_result = df_result[(df_result.관람료차이 == df_result.관람료차이.max())|(df_result.관람료차이 == df_result.관람료차이.min())]
check_04_03(df_result)

정답입니다! 10점 누적 되었습니다!
현재 누적 점수: 90 / 100

In [25]:
df_result.head(2)

                  어른관람료  어린이관람료  관람료차이
광역      박물관미술관구분
세종특별자치시 사립         2500    3000   -500
제주특별자치도 사립        10670    7710   2960

### 문제 4-4) 원하는 정보 얻기 04 (10점)
- 3단계의 DataFrame(df_target)을 이용하여 아래의 조건에 맞는 정보를 구하세요.
<br></br>
    - 가족(어른2, 청소년1, 어린이1)이 공휴일에 제주특별자치도 제주시에 있는 미술관을 관람하려 합니다. 총 관람료가 2만원 이하, 공휴일 4시간 이상 관람 가능한 미술관 list를 보여주세요.
<br></br>
<br></br>
    - 조건1: 가족(어른 2명, 청소년 1명, 어린이 1명)의 총 관람료가 2만원 이하여야 합니다.
<br></br>
    - 조건2: 제주특별자치도의 제주시에 있는 미술관을 가려고 합니다.
        - 미술관: 이 Test에서는 df_target의 시설명 Column(열)에 있는 data 중 <'미술관' 또는 '갤러리' 또는 '아트'> 라는 글자들이 포함되어 있는 곳을 '미술관'이라고 정의합니다.
<br></br>
    - 조건3: 공휴일에 가고자 합니다. 공휴일에 4시간 이상 관람 가능한 미술관이어야 합니다.
<br></br>
    - 조건4: 미술관 List의 Frame은 df_target과 동일합니다.
<br></br>
        - 예시: 서울특별시 송파구에서 가족(어른2, 청소년1, 어린이1)이 총 관람료 2만원 이내로 공휴일에 4시간 이상 관람할 수 있는 박물관 List
<br></br>
        <img src="./images/05-4-4-001.png" style="margin:auto" width=800/> 
<br></br>
    - 조건5: 'df_result' 변수에 결과 DataFrame을 할당하세요.
<br></br>
<br></br>
- 완료 후 결과 dataframe 변수(df_result)를 check_04_04 함수에 입력하여 채점하세요.

In [26]:
# 4-4

# 가족(어른2, 청소년1, 어린이1)이 공휴일에 제주특별자치도 서귀포시에 있는 미술관을 관람하려 합니다. 총 관람료가 2만원 이하, 공휴일 4시간 이상 관람 가능한 미술관 list를 보여주세요
budget = 20000
condition01 = df_target.어른관람료*2 + df_target.청소년관람료 + df_target.어린이관람료 < budget
condition02 = df_target.공휴일관람가능시간 >= 4
condition03 = df_target['기초']=='제주시'
condition04 = (df_target.시설명.str.contains('미술관'))|(df_target.시설명.str.contains('갤러리'))|(df_target.시설명.str.contains('아트'))
df_result = df_target[(condition01)&(condition02)&(condition03)&(condition04)]

check_04_04(df_result)

정답입니다! 10점 누적 되었습니다!
현재 누적 점수: 100 / 100

In [27]:
df_result.head(2)

,시설명,박물관미술관구분,소재지도로명주소,평일관람시작시각,평일관람종료시각,공휴일관람시작시각,공휴일관람종료시각,어른관람료,청소년관람료,어린이관람료,데이터기준일자,평일관람가능시간,공휴일관람가능시간,광역,기초,상세
1107,제주옹기 숨 미술관,사립,제주특별자치도 제주시 주르레길 55-19(해안동),10:00,17:00,10:00,17:00,0,0,0,2022-06-16,7.0,7.0,제주특별자치도,제주시,주르레길 55-19(해안동)
1185,제주도립미술관,공립,제주특별자치도 제주시 1100로 2894-78(연동),09:00,18:00,09:00,18:00,2000,1000,500,2022-06-16,9.0,9.0,제주특별자치도,제주시,1100로 2894-78(연동)